/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
    public static inline var ABattleAhead:String = "event:/Music/ABattleAhead";
    public static inline var ZombieFuel:String = "event:/Music/ZombieFuel";
}

class FmodSFX {
    public static inline var BulletTimeIn:String = "event:/SFX/BulletTimeIn";
    public static inline var BulletTimeOut:String = "event:/SFX/BulletTimeOut";
    public static inline var Campfire:String = "event:/SFX/Campfire";
    public static inline var CampfireFizzle:String = "event:/SFX/CampfireFizzle";
    public static inline var CampfireIgnite:String = "event:/SFX/CampfireIgnite";
    public static inline var CopShoot:String = "event:/SFX/CopShoot";
    public static inline var FiremanWater:String = "event:/SFX/FiremanWater";
    public static inline var HumanBurn:String = "event:/SFX/HumanBurn";
    public static inline var HumanKnockout:String = "event:/SFX/HumanKnockout";
    public static inline var LogHit:String = "event:/SFX/LogHit";
    public static inline var LogLand:String = "event:/SFX/LogLand";
    public static inline var MachoManDamage:String = "event:/SFX/MachoManDamage";
    public static inline var MachoManGrunt:String = "event:/SFX/MachoManGrunt";
    public static inline var MachoManGruntThrow:String = "event:/SFX/MachoManGruntThrow";
    public static inline var MachoManOhYeah:String = "event:/SFX/MachoManOhYeah";
    public static inline var MachoManThrowPunch:String = "event:/SFX/MachoManThrowPunch";
    public static inline var MenuNavigate:String = "event:/SFX/MenuNavigate";
    public static inline var MenuSelect:String = "event:/SFX/MenuSelect";
    public static inline var NecromancerRise:String = "event:/SFX/NecromancerRise";
    public static inline var RockGround:String = "event:/SFX/RockGround";
    public static inline var RockHit:String = "event:/SFX/RockHit";
    public static inline var TreePunch:String = "event:/SFX/TreePunch";
    public static inline var WoodFall:String = "event:/SFX/WoodFall";
    public static inline var ZombieAttack:String = "event:/SFX/ZombieAttack";
    public static inline var ZombieCrush:String = "event:/SFX/ZombieCrush";
    public static inline var ZombieGroan:String = "event:/SFX/ZombieGroan";
    public static inline var ZombieGroanLoud:String = "event:/SFX/ZombieGroanLoud";
    public static inline var ZombieHit:String = "event:/SFX/ZombieHit";
}
